name: ci-main
on:
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        HTTPIE_VERSION:
        - "3.0.0"
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: package
      run: source 10-package.sh
      env:
        HTTPIE_VERSION: ${{ matrix.HTTPIE_VERSION }}
        CONTAINER_REGISTRY_PUSH: 1
        CONTAINER_REGISTRY_PATH: registry-1.docker.io/conmob/httpie
        CONTAINER_REGISTRY_USERNAME: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
        CONTAINER_REGISTRY_PASSWORD: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
